name: Publish package and draft release

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  draft:
    name: Draft release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
