name: Check code quality before merge to develop

on:
  pull_request_target:
    branches:
      - develop

jobs:
  lint:
    name: Check code base before merge to develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Set up yarn
        run: npm install --global yarn

      - name: Set up dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

      - name: Compile lib
        run: yarn compile

      - name: Build bundle
        run: yarn build

      - name: Set up env.js
        run: node ./scripts/build-env.js --eth ${{ secrets.ETH_RPC }} --polygon ${{ secrets.POLYGON_RPC }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run tests
        run: yarn test
